{
 "title": "BOb Avg",
 "time": { "from": "2017-02-12T22:23:09.968Z", "to": "2017-02-13T18:30:23.311Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "SHOW TAG VALUES FROM \"agent_status\" WITH KEY = \"project\""
   },
   {
    "name": "resolution",
    "query": "10s,20s,30s,45s,1m,2m,3m,4m,5m.10m,15m,20m,25m,30m,1h,2h,3h,4h,5h,6h,12h,24h,"
   }
  ]
 },
 "panels": [
  {
   "title": "Backlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analyser Backlog",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "unrelayed windows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE \"relayed\" = False AND (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "relayed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "relayed windows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE \"relayed\" = True AND (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "relayed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Heatmap of unrelayed windows",
     "type": "petrslavotinek-carpetplot-panel",
     "gridPos": { "h": 12, "w": 9, "x": 12, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE \"relayed\" = False AND (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Unrelayed Windows",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Total Unrelayed Windows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE \"relayed\" = False AND (\"project\" =~ /^$project$/)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Relayed Windows",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Total Unrelayed Windows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE \"relayed\" = True AND (\"project\" =~ /^$project$/)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Windows",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Total Windows",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE (\"project\" =~ /^$project$/)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Telegrams",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Total Windows",
       "measurement": "agent_status",
       "query": "SELECT sum(\"count\")  / 1000000 FROM \"agent_status\" WHERE (\"project\" =~ /^$project$/)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 1000000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Amount Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Heatmap of windows",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "query": "SELECT count(\"relayed\") FROM \"agent_status\" WHERE (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Amount of Telegrams",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution of APCIs by Agent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col $tag_agent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apci",
     "query": "SELECT sum(*) AS \"\" FROM \"apci\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Change of Telegrams per Window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Telegram Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "telegram count $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_status",
       "query": "SELECT sum(\"count\") FROM \"agent_status\" WHERE (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval), \"agent\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "telegrams with unknown address $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unknown_addr",
       "select": [
        [
         { "params": [ "unknown_telegrams" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 2" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Distribution of APCIs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apci",
       "query": "SELECT sum(*) AS \"\" FROM \"apci\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Overall Outliers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "SVM world outliers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "LOF world outliers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Overall Inliers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "SVM world inliers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world_inlier" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "LOF world inliers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world_inlier" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[LOF] Outlier/Inlier Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "world outlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "world inlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world_inlier" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[SVM] Outlier/Inlier Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "world outlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "world inlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world_inlier" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ADDR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "[ADDR] Overall Unknown Addresses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "unknown source addresses $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unknown_addr",
       "select": [
        [
         { "params": [ "unknown_src_addr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "unknown destination addresses $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unknown_addr",
       "select": [
        [
         { "params": [ "unknown_dest_addr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[ADDR] Telegrams with Unknown Address",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "telegrams with unkown source address $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unknown_addr",
       "select": [
        [
         { "params": [ "unknown_src_telegrams" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "telegrams with unkown destination address $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unknown_addr",
       "select": [
        [
         { "params": [ "unknown_dest_telegrams" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "[SVM] Number of Outliers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "local outlier $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "local" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "world outlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "local" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[SVM] Avg Distance from Decision Surface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "distance $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "local_distance" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[SVM] Distance Spread",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "world distance spread",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "query": "SELECT max(\"world_distance\")-min(\"world_distance\") FROM \"svm\" WHERE (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "world_distance" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[SVM] Distance from Decision Surface Spread",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "max world distance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world_distance" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "min world distance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world_distance" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "avg world distance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "svm",
       "select": [
        [
         { "params": [ "world_distance" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LOF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "[LOF] Number of Outliers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "local outlier $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "local_inlier" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "world outlier",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[LOF]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "local LOF $tag_agent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "local_lof" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[LOF] Spread",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "LOF spread",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "query": "SELECT max(\"world_lof\") -min(\"world_lof\") FROM \"lof\" WHERE (\"project\" =~ /^$project$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "world_lof" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "-min()" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[LOF] Spread",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "max world LOF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world_lof" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "min world LOF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world_lof" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "avg world LOF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "lof",
       "select": [
        [
         { "params": [ "world_lof" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "[Entropy] Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "entropy1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "entropy2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[Entropy] Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "entropy avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "[Entropy] Spread",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "entropy max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "entropy min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "entropy avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "entropy",
       "select": [
        [
         { "params": [ "entropy" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}